### ISSUE TITLE
Using with Nuxt4

### ISSUE THREAD

**Issue by drewbaker** [lydell/strip-css-singleline-comments#1]
Hello! Would love to use this plugin with Nuxt 4 running Vite. On install and then running it I get this error. Using Node v22.8.0.

```
 Cannot start nuxt:  fn is not a function                                                                                                                 11:07:58 AM

  at stripCssSinglelineComments (node_modules/strip-css-singleline-comments/index.js:28:10)
  at resolveCSSOptions (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.BKSD0Otw.mjs:1198:32)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.BKSD0Otw.mjs:1683:14)
  at async bundle (node_modules/nuxt/dist/index.mjs:5902:5)
  at async build (node_modules/nuxt/dist/index.mjs:5777:3)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:6916:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:6806:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:6801:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:102:5)
  ```

**Comment by lydell** [comment]
Hi!

This module is not special in any way. It’s just a good old CommonJS module with `module.exports = a function`. This is not the place to ask for help with Nuxt.

Either way, this module is an old weekend hack that I never should have published to npm (I didn’t know better 9 years ago). I have deprecated the module now.
